events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        location /api/auth/ {
            proxy_pass http://auth-service:3001/;
        }
        location /api/products/ {
            proxy_pass http://product-service:3002/;
        }
        location /api/orders/ {
            proxy_pass http://order-service:3003/;
        }
        location /api/users/ {
            proxy_pass http://user-profile-service:3004/;
        }
        location /api/reviews/ {
            proxy_pass http://review-service:3005/;
        }
        location /api/audit/ {
            proxy_pass http://audit-service:3006/;
        }
    }
}