apiVersion: v1
kind: Secret
metadata:
  name: sre-secret
  namespace: app
type: Opaque
stringData:
  SECRET_KEY: my_secret_key
  AUTH_DATABASE_URL: postgresql://postgres:12345@postgres:5432/auth_db?sslmode=disable
  PRODUCT_DATABASE_URL: postgresql://postgres:12345@postgres:5432/product_db?sslmode=disable
  ORDER_DATABASE_URL: postgresql://postgres:12345@postgres:5432/order_db?sslmode=disable
  USER_DATABASE_URL: postgresql://postgres:12345@postgres:5432/user_db?sslmode=disable
  REVIEW_DATABASE_URL: postgresql://postgres:12345@postgres:5432/review_db?sslmode=disable
  AUDIT_DATABASE_URL: postgresql://postgres:12345@postgres:5432/audit_db?sslmode=disable